"""changed columns

Revision ID: 0e61ba3d867e
Revises: 75abb792f94b
Create Date: 2022-07-29 14:37:19.402458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e61ba3d867e'
down_revision = '75abb792f94b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
