"""Project Level Model Changes

Revision ID: 49f8e3c98eb2
Revises: a91d31fa4f02
Create Date: 2022-08-04 18:14:32.219671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f8e3c98eb2'
down_revision = 'a91d31fa4f02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
