"""Project Level Model Changes

Revision ID: 60117f2dd0d1
Revises: af8184fc8f7e
Create Date: 2022-08-04 18:39:42.522226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60117f2dd0d1'
down_revision = 'af8184fc8f7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
