"""Project Level Model Changes

Revision ID: 6d5f43c6490e
Revises: 60117f2dd0d1
Create Date: 2022-08-04 19:16:13.265750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5f43c6490e'
down_revision = '60117f2dd0d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
