"""created table for users

Revision ID: 80d14a269053
Revises: ff486d120562
Create Date: 2022-07-29 14:12:21.913132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d14a269053'
down_revision = 'ff486d120562'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('is_actives', sa.Boolean(), nullable=True))
    op.drop_column('doctors', 'is_activated')
    op.add_column('users', sa.Column('is_actives', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_activated')
    op.drop_column('users', 'news')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('news', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_activated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_actives')
    op.add_column('doctors', sa.Column('is_activated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('doctors', 'is_actives')
    # ### end Alembic commands ###
