"""Project Level Model Changes

Revision ID: a91d31fa4f02
Revises: 64d6bdbb04d2
Create Date: 2022-08-04 18:09:53.052803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91d31fa4f02'
down_revision = '64d6bdbb04d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
