"""Project Level Model Changes

Revision ID: af8184fc8f7e
Revises: f7165cb353a0
Create Date: 2022-08-04 18:24:07.529993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8184fc8f7e'
down_revision = 'f7165cb353a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
