"""Added New Model - Portfolio for Doctors

Revision ID: dbcf7b040656
Revises: 0e61ba3d867e
Create Date: 2022-07-29 16:43:36.913622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcf7b040656'
down_revision = '0e61ba3d867e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
