"""Project Level Model Changes

Revision ID: f7165cb353a0
Revises: 49f8e3c98eb2
Create Date: 2022-08-04 18:18:22.131782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7165cb353a0'
down_revision = '49f8e3c98eb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
